FROM node:20-alpine AS builder
WORKDIR /app
RUN npm i -g turbo
COPY turbo.json turbo.json
COPY package*.json .
COPY packages packages
COPY apps/mobile-service-authen apps/mobile-service-authen
RUN turbo prune --scope=mobile-service-authen --docker

FROM node:20-alpine AS installer
WORKDIR /app
RUN apk update
RUN apk add --no-cache libc6-compat
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json
RUN npm install
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
RUN npx turbo run build --filter=mobile-service-authen...
RUN npm install mysql2

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=installer /app .
WORKDIR /app/apps/mobile-service-authen

CMD ["dist/main.js"]
